### ISSUE TITLE
Unexpected output for function "projectCellTypeWithError" (negative estimated proportion)

### ISSUE THREAD

**Issue by meingoldchan** [ds420/CETYGO#3]
Hi,

Thank you so much for creating this helpful tool. We are trying to use the CETYGO score on our saliva sample and compare the accuracy of different reference panels. We used the `projectCellTypeWithError` function. We are expecting all the estimated proportion to be above zero given that the embedded function have included `nonnegative=TRUE`, 
`projectCellType <- function(Y, coefCellType, contrastCellType = NULL,
                                nonnegative = TRUE, lessThanOne = FALSE)`

However, some of the estimated cell type proportions are negative or larger than 1. See summary below:
`summary(predProp$Epithelial.cells)`

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/meingoldchan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/meingoldchan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Min. | 1st   Qu. | Median | Mean | 3rd Qu. | Max.
-- | -- | -- | -- | -- | --
-0.4005 | 0.2279 | 0.6528 | 0.5847 | 1.0088 | 1.1445

</body>

</html>

See output example below:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/meingoldchan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/meingoldchan/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Leukocytes | Epithelial.cells | CETYGO | nCGmissing
-- | -- | -- | --
-0.0943795 | 1.0292203 | 0.06595775 | 0
0.7681939 | 0.29432105 | 0.05096015 | 0
0.3714412 | 0.6142372 | 0.10218524 | 0
0.5685706 | 0.47044541 | 0.09227946 | 0
0.1008949 | 0.91788713 | 0.07719308 | 0
0.3567319 | 0.57364467 | 0.12703265 | 0
-0.1324865 | 1.10291455 | 0.05809814 | 0
0.9753393 | -0.0173235 | 0.06101208 | 0
1.0096531 | 0.10582623 | 0.07820359 | 0
0.5434531 | 0.49096942 | 0.11610091 | 0

</body>

</html>

Could you let us know whether this output is reasonable or produce by error? Your insight in how to interpret the result will be greatly appreciated.

Thank you,
Meingold

**Comment by ejh243** [comment]
Hi Meingold,

Looking at the code for the `projectCellTypeWithError ` function, I notice that the `nonnegative` and `lessThanOne` arguments are only enforced when there are more than 2 cell types to predict. So that explains why you see the results you do. As I did not write the original function, I am not sure if this is an oversight or a deliberate choice so I recommend you consult the minfi developers for further clarification.
